[package]
name = "hw01"
version = "0.1.0"
authors = ["Beacon Zhang <beacon1096@beacoworks.xyz>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.0.0-beta.2"
iced = "0.2"
nfd = "0.0.4"